/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq.tables.pojos;


import io.en4ble.examples.enums.ConferenceState;
import io.en4ble.pgaccess.dto.PointDTO;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * A simple conference.
 */
@io.swagger.v3.oas.annotations.media.Schema(name="ConferenceForm", title="A simple conference.")
public class ConferenceForm extends ConferenceDto implements Serializable, Cloneable {

    private static final long serialVersionUID = -72008707;


    @javax.validation.constraints.NotNull
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="id", required=true)
    @com.fasterxml.jackson.annotation.JsonProperty(value="id", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public UUID getId() {
        return super.getId();
    }

    @io.swagger.v3.oas.annotations.Hidden
    @com.fasterxml.jackson.annotation.JsonIgnore
    public LocalDateTime getCreated() {
        return super.getCreated();
    }

    @io.swagger.v3.oas.annotations.Hidden
    @com.fasterxml.jackson.annotation.JsonIgnore
    public LocalDateTime getUpdated() {
        return super.getUpdated();
    }

    /**
     * The name of the conference.
     */
    @javax.validation.constraints.NotNull
    @javax.validation.constraints.Size(min = 5, max = 30)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="name", title="The name of the conference.", required=true, minLength=5, maxLength=30)
    @com.fasterxml.jackson.annotation.JsonProperty(value="name", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getName() {
        return super.getName();
    }

    /**
     * The description of the conference.
     */
    @javax.validation.constraints.Size(min = 20, max = 2000)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="about", title="The description of the conference.", minLength=20, maxLength=2000)
    @com.fasterxml.jackson.annotation.JsonProperty(value="about", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getAbout() {
        return super.getAbout();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="startDate")
    @com.fasterxml.jackson.annotation.JsonProperty(value="startDate", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate getStartDate() {
        return super.getStartDate();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="endDate")
    @com.fasterxml.jackson.annotation.JsonProperty(value="endDate", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate getEndDate() {
        return super.getEndDate();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_ONLY, name="state", title="", defaultValue="NEW")
    @com.fasterxml.jackson.annotation.JsonProperty(value="state", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_ONLY)
    public ConferenceState getState() {
        return super.getState();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="location")
    @com.fasterxml.jackson.annotation.JsonProperty(value="location", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PointDTO getLocation() {
        return super.getLocation();
    }
}
