/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq.tables.pojos;


import io.en4ble.examples.enums.ConferenceState;
import io.en4ble.pgaccess.dto.PointDTO;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@io.swagger.v3.oas.annotations.media.Schema(name="ConferenceV1Dto")
public class ConferenceV1Dto extends Object implements Serializable, Cloneable {

    private static final long serialVersionUID = 2117372454;

    private UUID            id;
    private String          name;
    private String          about;
    private LocalDate       startDate;
    private LocalDate       endDate;
    private PointDTO        location;
    private ConferenceState state;

    public ConferenceV1Dto() {}

    public ConferenceV1Dto(ConferenceV1Dto value) {
        this.id = value.id;
        this.name = value.name;
        this.about = value.about;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.location = value.location;
        this.state = value.state;
    }

    public ConferenceV1Dto(
        UUID            id,
        String          name,
        String          about,
        LocalDate       startDate,
        LocalDate       endDate,
        PointDTO        location,
        ConferenceState state
    ) {
        this.id = id;
        this.name = name;
        this.about = about;
        this.startDate = startDate;
        this.endDate = endDate;
        this.location = location;
        this.state = state;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="id")
    @com.fasterxml.jackson.annotation.JsonProperty(value="id", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public UUID getId() {
        return this.id;
    }

    public ConferenceV1Dto setId(UUID id) {
        this.id = id;
        return this;
    }

    @org.hibernate.validator.constraints.Length(max = 30)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="name", maxLength=30)
    @com.fasterxml.jackson.annotation.JsonProperty(value="name", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getName() {
        return this.name;
    }

    public ConferenceV1Dto setName(String name) {
        this.name = name;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="about")
    @com.fasterxml.jackson.annotation.JsonProperty(value="about", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getAbout() {
        return this.about;
    }

    public ConferenceV1Dto setAbout(String about) {
        this.about = about;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="startDate")
    @com.fasterxml.jackson.annotation.JsonProperty(value="startDate", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate getStartDate() {
        return this.startDate;
    }

    public ConferenceV1Dto setStartDate(LocalDate startDate) {
        this.startDate = startDate;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="endDate")
    @com.fasterxml.jackson.annotation.JsonProperty(value="endDate", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate getEndDate() {
        return this.endDate;
    }

    public ConferenceV1Dto setEndDate(LocalDate endDate) {
        this.endDate = endDate;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="location")
    @com.fasterxml.jackson.annotation.JsonProperty(value="location", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PointDTO getLocation() {
        return this.location;
    }

    public ConferenceV1Dto setLocation(PointDTO location) {
        this.location = location;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="state")
    @com.fasterxml.jackson.annotation.JsonProperty(value="state", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public ConferenceState getState() {
        return this.state;
    }

    public ConferenceV1Dto setState(ConferenceState state) {
        this.state = state;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConferenceV1Dto (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(about);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(location);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
