/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq.tables.pojos;


import io.en4ble.examples.enums.ConferenceState;
import io.en4ble.pgaccess.dto.PointDTO;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@io.swagger.v3.oas.annotations.media.Schema(name="ConferenceV1Form")
public class ConferenceV1Form extends ConferenceV1Dto implements Serializable, Cloneable {

    private static final long serialVersionUID = 399960728;


    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="id")
    @com.fasterxml.jackson.annotation.JsonProperty(value="id", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public UUID getId() {
        return super.getId();
    }

    @javax.validation.constraints.Size(max = 30)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="name", maxLength=30)
    @com.fasterxml.jackson.annotation.JsonProperty(value="name", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getName() {
        return super.getName();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="about")
    @com.fasterxml.jackson.annotation.JsonProperty(value="about", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getAbout() {
        return super.getAbout();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="startDate")
    @com.fasterxml.jackson.annotation.JsonProperty(value="startDate", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate getStartDate() {
        return super.getStartDate();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="endDate")
    @com.fasterxml.jackson.annotation.JsonProperty(value="endDate", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate getEndDate() {
        return super.getEndDate();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="location")
    @com.fasterxml.jackson.annotation.JsonProperty(value="location", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PointDTO getLocation() {
        return super.getLocation();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="state")
    @com.fasterxml.jackson.annotation.JsonProperty(value="state", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public ConferenceState getState() {
        return super.getState();
    }
}
