/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq.tables.pojos;


import io.en4ble.pgaccess.dto.BoxDTO;
import io.en4ble.pgaccess.dto.CircleDTO;
import io.en4ble.pgaccess.dto.LineDTO;
import io.en4ble.pgaccess.dto.LineSegmentDTO;
import io.en4ble.pgaccess.dto.PathDTO;
import io.en4ble.pgaccess.dto.PointDTO;
import io.en4ble.pgaccess.dto.PolygonDTO;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.util.UUID;


/**
 * An example table containing all datatypes that are supported by reactive-pg-access.
 */
@io.swagger.v3.oas.annotations.media.Schema(name="ExampleForm", title="An example table containing all datatypes that are supported by reactive-pg-access.")
public class ExampleForm extends ExampleDto implements Serializable, Cloneable {

    private static final long serialVersionUID = 1682494923;


    @javax.validation.constraints.NotNull
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="uuid", required=true)
    @com.fasterxml.jackson.annotation.JsonProperty(value="uuid", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public UUID getUuid() {
        return super.getUuid();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="uuidArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="uuidArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public UUID[] getUuidArray() {
        return super.getUuidArray();
    }

    @org.hibernate.validator.constraints.Length(min = 10, max = 200)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="text", title="", minLength=10, maxLength=200)
    @com.fasterxml.jackson.annotation.JsonProperty(value="text", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getText() {
        return super.getText();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="textArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="textArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String[] getTextArray() {
        return super.getTextArray();
    }

    @org.hibernate.validator.constraints.Length(min = 4, max = 20)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="string", title="", minLength=4, maxLength=20)
    @com.fasterxml.jackson.annotation.JsonProperty(value="string", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getString() {
        return super.getString();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="stringArray", maxLength=20)
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="stringArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String[] getStringArray() {
        return super.getStringArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="shortValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Short getShortValue() {
        return super.getShortValue();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="shortArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Short[] getShortArray() {
        return super.getShortArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="integerValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="integerValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Integer getIntegerValue() {
        return super.getIntegerValue();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="integerArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="integerArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Integer[] getIntegerArray() {
        return super.getIntegerArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="longValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Long getLongValue() {
        return super.getLongValue();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="longArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Long[] getLongArray() {
        return super.getLongArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="floatValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="floatValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Float getFloatValue() {
        return super.getFloatValue();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="floatArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="floatArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Float[] getFloatArray() {
        return super.getFloatArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="doubleValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="doubleValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Double getDoubleValue() {
        return super.getDoubleValue();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="doubleArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="doubleArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Double[] getDoubleArray() {
        return super.getDoubleArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="booleanValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="booleanValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Boolean getBooleanValue() {
        return super.getBooleanValue();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="booleanArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="booleanArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Boolean[] getBooleanArray() {
        return super.getBooleanArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="date")
    @com.fasterxml.jackson.annotation.JsonProperty(value="date", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate getDate() {
        return super.getDate();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate[] getDateArray() {
        return super.getDateArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="time")
    @com.fasterxml.jackson.annotation.JsonProperty(value="time", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalTime getTime() {
        return super.getTime();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timeArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="timeArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalTime[] getTimeArray() {
        return super.getTimeArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timetz")
    @com.fasterxml.jackson.annotation.JsonProperty(value="timetz", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public OffsetTime getTimetz() {
        return super.getTimetz();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timetzArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="timetzArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public OffsetTime[] getTimetzArray() {
        return super.getTimetzArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTime")
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateTime", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDateTime getDateTime() {
        return super.getDateTime();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimeArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateTimeArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDateTime[] getDateTimeArray() {
        return super.getDateTimeArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimetz")
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateTimetz", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public OffsetDateTime getDateTimetz() {
        return super.getDateTimetz();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimetzArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateTimetzArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public OffsetDateTime[] getDateTimetzArray() {
        return super.getDateTimetzArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="point")
    @com.fasterxml.jackson.annotation.JsonProperty(value="point", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PointDTO getPoint() {
        return super.getPoint();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="pointArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="pointArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PointDTO[] getPointArray() {
        return super.getPointArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="line")
    @com.fasterxml.jackson.annotation.JsonProperty(value="line", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LineDTO getLine() {
        return super.getLine();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="lineArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LineDTO[] getLineArray() {
        return super.getLineArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineSegment")
    @com.fasterxml.jackson.annotation.JsonProperty(value="lineSegment", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LineSegmentDTO getLineSegment() {
        return super.getLineSegment();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineSegmentArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="lineSegmentArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LineSegmentDTO[] getLineSegmentArray() {
        return super.getLineSegmentArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="box")
    @com.fasterxml.jackson.annotation.JsonProperty(value="box", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public BoxDTO getBox() {
        return super.getBox();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="boxArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="boxArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public BoxDTO[] getBoxArray() {
        return super.getBoxArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="path")
    @com.fasterxml.jackson.annotation.JsonProperty(value="path", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PathDTO getPath() {
        return super.getPath();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="pathArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="pathArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PathDTO[] getPathArray() {
        return super.getPathArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="polygon")
    @com.fasterxml.jackson.annotation.JsonProperty(value="polygon", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PolygonDTO getPolygon() {
        return super.getPolygon();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="polygonArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="polygonArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PolygonDTO[] getPolygonArray() {
        return super.getPolygonArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="circle")
    @com.fasterxml.jackson.annotation.JsonProperty(value="circle", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public CircleDTO getCircle() {
        return super.getCircle();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="circleArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="circleArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public CircleDTO[] getCircleArray() {
        return super.getCircleArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="name")
    @com.fasterxml.jackson.annotation.JsonProperty(value="name", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getName() {
        return super.getName();
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="nameArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="nameArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String[] getNameArray() {
        return super.getNameArray();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortSerial", defaultValue="extval(")
    @com.fasterxml.jackson.annotation.JsonProperty(value="shortSerial", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Short getShortSerial() {
        return super.getShortSerial();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="serial", defaultValue="extval(")
    @com.fasterxml.jackson.annotation.JsonProperty(value="serial", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Integer getSerial() {
        return super.getSerial();
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longSerial", defaultValue="extval(")
    @com.fasterxml.jackson.annotation.JsonProperty(value="longSerial", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Long getLongSerial() {
        return super.getLongSerial();
    }

    @org.hibernate.validator.constraints.Length(max = 3)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="state", maxLength=3, defaultValue="new")
    @com.fasterxml.jackson.annotation.JsonProperty(value="state", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getState() {
        return super.getState();
    }
}
