/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq.tables.pojos;


import io.en4ble.pgaccess.dto.BoxDTO;
import io.en4ble.pgaccess.dto.CircleDTO;
import io.en4ble.pgaccess.dto.LineDTO;
import io.en4ble.pgaccess.dto.LineSegmentDTO;
import io.en4ble.pgaccess.dto.PathDTO;
import io.en4ble.pgaccess.dto.PointDTO;
import io.en4ble.pgaccess.dto.PolygonDTO;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.util.Arrays;
import java.util.UUID;


/**
 * An example table containing all datatypes that are supported by reactive-pg-access.
 */
@io.swagger.v3.oas.annotations.media.Schema(name="ExampleDto", title="An example table containing all datatypes that are supported by reactive-pg-access.")
public class ExampleDto extends Object implements Serializable, Cloneable {

    private static final long serialVersionUID = -949808875;

    private UUID             uuid;
    private UUID[]           uuidArray;
    private String           text;
    private String[]         textArray;
    private String           string;
    private String[]         stringArray;
    private Short            shortValue;
    private Short[]          shortArray;
    private Integer          integerValue;
    private Integer[]        integerArray;
    private Long             longValue;
    private Long[]           longArray;
    private Float            floatValue;
    private Float[]          floatArray;
    private Double           doubleValue;
    private Double[]         doubleArray;
    private Boolean          booleanValue;
    private Boolean[]        booleanArray;
    private LocalDate        date;
    private LocalDate[]      dateArray;
    private LocalTime        time;
    private LocalTime[]      timeArray;
    private OffsetTime       timetz;
    private OffsetTime[]     timetzArray;
    private LocalDateTime    dateTime;
    private LocalDateTime[]  dateTimeArray;
    private OffsetDateTime   dateTimetz;
    private OffsetDateTime[] dateTimetzArray;
    private PointDTO         point;
    private PointDTO[]       pointArray;
    private LineDTO          line;
    private LineDTO[]        lineArray;
    private LineSegmentDTO   lineSegment;
    private LineSegmentDTO[] lineSegmentArray;
    private BoxDTO           box;
    private BoxDTO[]         boxArray;
    private PathDTO          path;
    private PathDTO[]        pathArray;
    private PolygonDTO       polygon;
    private PolygonDTO[]     polygonArray;
    private CircleDTO        circle;
    private CircleDTO[]      circleArray;
    private String           name;
    private String[]         nameArray;
    private Short            shortSerial;
    private Integer          serial;
    private Long             longSerial;
    private String           state;

    public ExampleDto() {}

    public ExampleDto(ExampleDto value) {
        this.uuid = value.uuid;
        this.uuidArray = value.uuidArray;
        this.text = value.text;
        this.textArray = value.textArray;
        this.string = value.string;
        this.stringArray = value.stringArray;
        this.shortValue = value.shortValue;
        this.shortArray = value.shortArray;
        this.integerValue = value.integerValue;
        this.integerArray = value.integerArray;
        this.longValue = value.longValue;
        this.longArray = value.longArray;
        this.floatValue = value.floatValue;
        this.floatArray = value.floatArray;
        this.doubleValue = value.doubleValue;
        this.doubleArray = value.doubleArray;
        this.booleanValue = value.booleanValue;
        this.booleanArray = value.booleanArray;
        this.date = value.date;
        this.dateArray = value.dateArray;
        this.time = value.time;
        this.timeArray = value.timeArray;
        this.timetz = value.timetz;
        this.timetzArray = value.timetzArray;
        this.dateTime = value.dateTime;
        this.dateTimeArray = value.dateTimeArray;
        this.dateTimetz = value.dateTimetz;
        this.dateTimetzArray = value.dateTimetzArray;
        this.point = value.point;
        this.pointArray = value.pointArray;
        this.line = value.line;
        this.lineArray = value.lineArray;
        this.lineSegment = value.lineSegment;
        this.lineSegmentArray = value.lineSegmentArray;
        this.box = value.box;
        this.boxArray = value.boxArray;
        this.path = value.path;
        this.pathArray = value.pathArray;
        this.polygon = value.polygon;
        this.polygonArray = value.polygonArray;
        this.circle = value.circle;
        this.circleArray = value.circleArray;
        this.name = value.name;
        this.nameArray = value.nameArray;
        this.shortSerial = value.shortSerial;
        this.serial = value.serial;
        this.longSerial = value.longSerial;
        this.state = value.state;
    }

    public ExampleDto(
        UUID             uuid,
        UUID[]           uuidArray,
        String           text,
        String[]         textArray,
        String           string,
        String[]         stringArray,
        Short            shortValue,
        Short[]          shortArray,
        Integer          integerValue,
        Integer[]        integerArray,
        Long             longValue,
        Long[]           longArray,
        Float            floatValue,
        Float[]          floatArray,
        Double           doubleValue,
        Double[]         doubleArray,
        Boolean          booleanValue,
        Boolean[]        booleanArray,
        LocalDate        date,
        LocalDate[]      dateArray,
        LocalTime        time,
        LocalTime[]      timeArray,
        OffsetTime       timetz,
        OffsetTime[]     timetzArray,
        LocalDateTime    dateTime,
        LocalDateTime[]  dateTimeArray,
        OffsetDateTime   dateTimetz,
        OffsetDateTime[] dateTimetzArray,
        PointDTO         point,
        PointDTO[]       pointArray,
        LineDTO          line,
        LineDTO[]        lineArray,
        LineSegmentDTO   lineSegment,
        LineSegmentDTO[] lineSegmentArray,
        BoxDTO           box,
        BoxDTO[]         boxArray,
        PathDTO          path,
        PathDTO[]        pathArray,
        PolygonDTO       polygon,
        PolygonDTO[]     polygonArray,
        CircleDTO        circle,
        CircleDTO[]      circleArray,
        String           name,
        String[]         nameArray,
        Short            shortSerial,
        Integer          serial,
        Long             longSerial,
        String           state
    ) {
        this.uuid = uuid;
        this.uuidArray = uuidArray;
        this.text = text;
        this.textArray = textArray;
        this.string = string;
        this.stringArray = stringArray;
        this.shortValue = shortValue;
        this.shortArray = shortArray;
        this.integerValue = integerValue;
        this.integerArray = integerArray;
        this.longValue = longValue;
        this.longArray = longArray;
        this.floatValue = floatValue;
        this.floatArray = floatArray;
        this.doubleValue = doubleValue;
        this.doubleArray = doubleArray;
        this.booleanValue = booleanValue;
        this.booleanArray = booleanArray;
        this.date = date;
        this.dateArray = dateArray;
        this.time = time;
        this.timeArray = timeArray;
        this.timetz = timetz;
        this.timetzArray = timetzArray;
        this.dateTime = dateTime;
        this.dateTimeArray = dateTimeArray;
        this.dateTimetz = dateTimetz;
        this.dateTimetzArray = dateTimetzArray;
        this.point = point;
        this.pointArray = pointArray;
        this.line = line;
        this.lineArray = lineArray;
        this.lineSegment = lineSegment;
        this.lineSegmentArray = lineSegmentArray;
        this.box = box;
        this.boxArray = boxArray;
        this.path = path;
        this.pathArray = pathArray;
        this.polygon = polygon;
        this.polygonArray = polygonArray;
        this.circle = circle;
        this.circleArray = circleArray;
        this.name = name;
        this.nameArray = nameArray;
        this.shortSerial = shortSerial;
        this.serial = serial;
        this.longSerial = longSerial;
        this.state = state;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="uuid")
    @com.fasterxml.jackson.annotation.JsonProperty(value="uuid", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public UUID getUuid() {
        return this.uuid;
    }

    public ExampleDto setUuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="uuidArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="uuidArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public UUID[] getUuidArray() {
        return this.uuidArray;
    }

    public ExampleDto setUuidArray(UUID... uuidArray) {
        this.uuidArray = uuidArray;
        return this;
    }

    @javax.validation.constraints.Size(min = 10, max = 200)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="text", title="", minLength=10, maxLength=200)
    @com.fasterxml.jackson.annotation.JsonProperty(value="text", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getText() {
        return this.text;
    }

    public ExampleDto setText(String text) {
        this.text = text;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="textArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="textArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String[] getTextArray() {
        return this.textArray;
    }

    public ExampleDto setTextArray(String... textArray) {
        this.textArray = textArray;
        return this;
    }

    @javax.validation.constraints.Size(min = 4, max = 20)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="string", title="", minLength=4, maxLength=20)
    @com.fasterxml.jackson.annotation.JsonProperty(value="string", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getString() {
        return this.string;
    }

    public ExampleDto setString(String string) {
        this.string = string;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="stringArray", maxLength=20)
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="stringArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String[] getStringArray() {
        return this.stringArray;
    }

    public ExampleDto setStringArray(String... stringArray) {
        this.stringArray = stringArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="shortValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Short getShortValue() {
        return this.shortValue;
    }

    public ExampleDto setShortValue(Short shortValue) {
        this.shortValue = shortValue;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="shortArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Short[] getShortArray() {
        return this.shortArray;
    }

    public ExampleDto setShortArray(Short... shortArray) {
        this.shortArray = shortArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="integerValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="integerValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Integer getIntegerValue() {
        return this.integerValue;
    }

    public ExampleDto setIntegerValue(Integer integerValue) {
        this.integerValue = integerValue;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="integerArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="integerArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Integer[] getIntegerArray() {
        return this.integerArray;
    }

    public ExampleDto setIntegerArray(Integer... integerArray) {
        this.integerArray = integerArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="longValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Long getLongValue() {
        return this.longValue;
    }

    public ExampleDto setLongValue(Long longValue) {
        this.longValue = longValue;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="longArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Long[] getLongArray() {
        return this.longArray;
    }

    public ExampleDto setLongArray(Long... longArray) {
        this.longArray = longArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="floatValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="floatValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Float getFloatValue() {
        return this.floatValue;
    }

    public ExampleDto setFloatValue(Float floatValue) {
        this.floatValue = floatValue;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="floatArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="floatArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Float[] getFloatArray() {
        return this.floatArray;
    }

    public ExampleDto setFloatArray(Float... floatArray) {
        this.floatArray = floatArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="doubleValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="doubleValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Double getDoubleValue() {
        return this.doubleValue;
    }

    public ExampleDto setDoubleValue(Double doubleValue) {
        this.doubleValue = doubleValue;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="doubleArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="doubleArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Double[] getDoubleArray() {
        return this.doubleArray;
    }

    public ExampleDto setDoubleArray(Double... doubleArray) {
        this.doubleArray = doubleArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="booleanValue")
    @com.fasterxml.jackson.annotation.JsonProperty(value="booleanValue", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Boolean getBooleanValue() {
        return this.booleanValue;
    }

    public ExampleDto setBooleanValue(Boolean booleanValue) {
        this.booleanValue = booleanValue;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="booleanArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="booleanArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Boolean[] getBooleanArray() {
        return this.booleanArray;
    }

    public ExampleDto setBooleanArray(Boolean... booleanArray) {
        this.booleanArray = booleanArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="date")
    @com.fasterxml.jackson.annotation.JsonProperty(value="date", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate getDate() {
        return this.date;
    }

    public ExampleDto setDate(LocalDate date) {
        this.date = date;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDate[] getDateArray() {
        return this.dateArray;
    }

    public ExampleDto setDateArray(LocalDate... dateArray) {
        this.dateArray = dateArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="time")
    @com.fasterxml.jackson.annotation.JsonProperty(value="time", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalTime getTime() {
        return this.time;
    }

    public ExampleDto setTime(LocalTime time) {
        this.time = time;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timeArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="timeArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalTime[] getTimeArray() {
        return this.timeArray;
    }

    public ExampleDto setTimeArray(LocalTime... timeArray) {
        this.timeArray = timeArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timetz")
    @com.fasterxml.jackson.annotation.JsonProperty(value="timetz", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public OffsetTime getTimetz() {
        return this.timetz;
    }

    public ExampleDto setTimetz(OffsetTime timetz) {
        this.timetz = timetz;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timetzArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="timetzArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public OffsetTime[] getTimetzArray() {
        return this.timetzArray;
    }

    public ExampleDto setTimetzArray(OffsetTime... timetzArray) {
        this.timetzArray = timetzArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTime")
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateTime", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }

    public ExampleDto setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimeArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateTimeArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LocalDateTime[] getDateTimeArray() {
        return this.dateTimeArray;
    }

    public ExampleDto setDateTimeArray(LocalDateTime... dateTimeArray) {
        this.dateTimeArray = dateTimeArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimetz")
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateTimetz", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public OffsetDateTime getDateTimetz() {
        return this.dateTimetz;
    }

    public ExampleDto setDateTimetz(OffsetDateTime dateTimetz) {
        this.dateTimetz = dateTimetz;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimetzArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="dateTimetzArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public OffsetDateTime[] getDateTimetzArray() {
        return this.dateTimetzArray;
    }

    public ExampleDto setDateTimetzArray(OffsetDateTime... dateTimetzArray) {
        this.dateTimetzArray = dateTimetzArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="point")
    @com.fasterxml.jackson.annotation.JsonProperty(value="point", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PointDTO getPoint() {
        return this.point;
    }

    public ExampleDto setPoint(PointDTO point) {
        this.point = point;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="pointArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="pointArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PointDTO[] getPointArray() {
        return this.pointArray;
    }

    public ExampleDto setPointArray(PointDTO... pointArray) {
        this.pointArray = pointArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="line")
    @com.fasterxml.jackson.annotation.JsonProperty(value="line", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LineDTO getLine() {
        return this.line;
    }

    public ExampleDto setLine(LineDTO line) {
        this.line = line;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="lineArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LineDTO[] getLineArray() {
        return this.lineArray;
    }

    public ExampleDto setLineArray(LineDTO... lineArray) {
        this.lineArray = lineArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineSegment")
    @com.fasterxml.jackson.annotation.JsonProperty(value="lineSegment", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LineSegmentDTO getLineSegment() {
        return this.lineSegment;
    }

    public ExampleDto setLineSegment(LineSegmentDTO lineSegment) {
        this.lineSegment = lineSegment;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineSegmentArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="lineSegmentArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public LineSegmentDTO[] getLineSegmentArray() {
        return this.lineSegmentArray;
    }

    public ExampleDto setLineSegmentArray(LineSegmentDTO... lineSegmentArray) {
        this.lineSegmentArray = lineSegmentArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="box")
    @com.fasterxml.jackson.annotation.JsonProperty(value="box", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public BoxDTO getBox() {
        return this.box;
    }

    public ExampleDto setBox(BoxDTO box) {
        this.box = box;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="boxArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="boxArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public BoxDTO[] getBoxArray() {
        return this.boxArray;
    }

    public ExampleDto setBoxArray(BoxDTO... boxArray) {
        this.boxArray = boxArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="path")
    @com.fasterxml.jackson.annotation.JsonProperty(value="path", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PathDTO getPath() {
        return this.path;
    }

    public ExampleDto setPath(PathDTO path) {
        this.path = path;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="pathArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="pathArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PathDTO[] getPathArray() {
        return this.pathArray;
    }

    public ExampleDto setPathArray(PathDTO... pathArray) {
        this.pathArray = pathArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="polygon")
    @com.fasterxml.jackson.annotation.JsonProperty(value="polygon", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PolygonDTO getPolygon() {
        return this.polygon;
    }

    public ExampleDto setPolygon(PolygonDTO polygon) {
        this.polygon = polygon;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="polygonArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="polygonArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public PolygonDTO[] getPolygonArray() {
        return this.polygonArray;
    }

    public ExampleDto setPolygonArray(PolygonDTO... polygonArray) {
        this.polygonArray = polygonArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="circle")
    @com.fasterxml.jackson.annotation.JsonProperty(value="circle", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public CircleDTO getCircle() {
        return this.circle;
    }

    public ExampleDto setCircle(CircleDTO circle) {
        this.circle = circle;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="circleArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="circleArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public CircleDTO[] getCircleArray() {
        return this.circleArray;
    }

    public ExampleDto setCircleArray(CircleDTO... circleArray) {
        this.circleArray = circleArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="name")
    @com.fasterxml.jackson.annotation.JsonProperty(value="name", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getName() {
        return this.name;
    }

    public ExampleDto setName(String name) {
        this.name = name;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.ArraySchema(schema = 
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="nameArray")
    )
    @com.fasterxml.jackson.annotation.JsonProperty(value="nameArray", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String[] getNameArray() {
        return this.nameArray;
    }

    public ExampleDto setNameArray(String... nameArray) {
        this.nameArray = nameArray;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortSerial")
    @com.fasterxml.jackson.annotation.JsonProperty(value="shortSerial", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Short getShortSerial() {
        return this.shortSerial;
    }

    public ExampleDto setShortSerial(Short shortSerial) {
        this.shortSerial = shortSerial;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="serial")
    @com.fasterxml.jackson.annotation.JsonProperty(value="serial", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Integer getSerial() {
        return this.serial;
    }

    public ExampleDto setSerial(Integer serial) {
        this.serial = serial;
        return this;
    }

    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longSerial")
    @com.fasterxml.jackson.annotation.JsonProperty(value="longSerial", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public Long getLongSerial() {
        return this.longSerial;
    }

    public ExampleDto setLongSerial(Long longSerial) {
        this.longSerial = longSerial;
        return this;
    }

    @javax.validation.constraints.Size(max = 3)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="state", maxLength=3)
    @com.fasterxml.jackson.annotation.JsonProperty(value="state", access = com.fasterxml.jackson.annotation.JsonProperty.Access.READ_WRITE)
    public String getState() {
        return this.state;
    }

    public ExampleDto setState(String state) {
        this.state = state;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExampleDto (");

        sb.append(uuid);
        sb.append(", ").append(Arrays.toString(uuidArray));
        sb.append(", ").append(text);
        sb.append(", ").append(Arrays.toString(textArray));
        sb.append(", ").append(string);
        sb.append(", ").append(Arrays.toString(stringArray));
        sb.append(", ").append(shortValue);
        sb.append(", ").append(Arrays.toString(shortArray));
        sb.append(", ").append(integerValue);
        sb.append(", ").append(Arrays.toString(integerArray));
        sb.append(", ").append(longValue);
        sb.append(", ").append(Arrays.toString(longArray));
        sb.append(", ").append(floatValue);
        sb.append(", ").append(Arrays.toString(floatArray));
        sb.append(", ").append(doubleValue);
        sb.append(", ").append(Arrays.toString(doubleArray));
        sb.append(", ").append(booleanValue);
        sb.append(", ").append(Arrays.toString(booleanArray));
        sb.append(", ").append(date);
        sb.append(", ").append(Arrays.toString(dateArray));
        sb.append(", ").append(time);
        sb.append(", ").append(Arrays.toString(timeArray));
        sb.append(", ").append(timetz);
        sb.append(", ").append(Arrays.toString(timetzArray));
        sb.append(", ").append(dateTime);
        sb.append(", ").append(Arrays.toString(dateTimeArray));
        sb.append(", ").append(dateTimetz);
        sb.append(", ").append(Arrays.toString(dateTimetzArray));
        sb.append(", ").append(point);
        sb.append(", ").append(Arrays.toString(pointArray));
        sb.append(", ").append(line);
        sb.append(", ").append(Arrays.toString(lineArray));
        sb.append(", ").append(lineSegment);
        sb.append(", ").append(Arrays.toString(lineSegmentArray));
        sb.append(", ").append(box);
        sb.append(", ").append(Arrays.toString(boxArray));
        sb.append(", ").append(path);
        sb.append(", ").append(Arrays.toString(pathArray));
        sb.append(", ").append(polygon);
        sb.append(", ").append(Arrays.toString(polygonArray));
        sb.append(", ").append(circle);
        sb.append(", ").append(Arrays.toString(circleArray));
        sb.append(", ").append(name);
        sb.append(", ").append(Arrays.toString(nameArray));
        sb.append(", ").append(shortSerial);
        sb.append(", ").append(serial);
        sb.append(", ").append(longSerial);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
