/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq;


import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
public class DefaultCatalog extends CatalogImpl implements Serializable, Cloneable {

    private static final long serialVersionUID = -2008487988;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>pgaccess</code>.
     */
    public final Pgaccess PGACCESS = io.en4ble.examples.jooq.Pgaccess.PGACCESS;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
            Pgaccess.PGACCESS);
    }
}
