/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq;


import io.en4ble.examples.jooq.tables.Conference;
import io.en4ble.examples.jooq.tables.Example;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>pgaccess</code> schema.
 */
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONFERENCE_PK = Indexes0.CONFERENCE_PK;
    public static final Index EXAMPLE_PK = Indexes0.EXAMPLE_PK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONFERENCE_PK = Internal.createIndex("t_conference_pk", Conference.CONFERENCE, new OrderField[] { Conference.CONFERENCE.ID }, true);
        public static Index EXAMPLE_PK = Internal.createIndex("p_example_pk", Example.EXAMPLE, new OrderField[] { Example.EXAMPLE.UUID }, true);
    }
}
