/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq;


import io.en4ble.examples.jooq.tables.Conference;
import io.en4ble.examples.jooq.tables.ConferenceV1;
import io.en4ble.examples.jooq.tables.Example;


/**
 * Convenience access to all tables in pgaccess
 */
public class Tables {

    /**
     * The table <code>pgaccess.conference_v1</code>.
     */
    public static final ConferenceV1 CONFERENCE_V1 = io.en4ble.examples.jooq.tables.ConferenceV1.CONFERENCE_V1;

    /**
     * A simple conference.
     */
    public static final Conference CONFERENCE = io.en4ble.examples.jooq.tables.Conference.CONFERENCE;

    /**
     * An example table containing all datatypes that are supported by reactive-pg-access.
     */
    public static final Example EXAMPLE = io.en4ble.examples.jooq.tables.Example.EXAMPLE;
}
