/*
 * This file is generated by jOOQ.
 */
package io.en4ble.examples.jooq.tables.records;


import io.en4ble.examples.dto.TestDTO;
import io.en4ble.examples.jooq.tables.Example;
import io.en4ble.pgaccess.dto.BoxDTO;
import io.en4ble.pgaccess.dto.CircleDTO;
import io.en4ble.pgaccess.dto.IntervalDTO;
import io.en4ble.pgaccess.dto.LineDTO;
import io.en4ble.pgaccess.dto.LineSegmentDTO;
import io.en4ble.pgaccess.dto.PathDTO;
import io.en4ble.pgaccess.dto.PointDTO;
import io.en4ble.pgaccess.dto.PolygonDTO;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * An example table containing all datatypes that are supported by reactive-pg-access.
 */
@io.swagger.v3.oas.annotations.media.Schema(name="Example", title="An example table containing all datatypes that are supported by reactive-pg-access.")
public class ExampleRecord extends UpdatableRecordImpl<ExampleRecord> implements Serializable, Cloneable {

    private static final long serialVersionUID = 1253223103;

    /**
     * Setter for <code>pgaccess.p_example.e_uuid</code>.
     */
    public ExampleRecord setUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_uuid</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="uuid")
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_uuid_array</code>.
     */
    public ExampleRecord setUuidArray(UUID... value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_uuid_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="uuidArray")
    public UUID[] getUuidArray() {
        return (UUID[]) get(1);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_text</code>. {{minLength=10}}{{maxLength=200}}
     */
    public ExampleRecord setText(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_text</code>. {{minLength=10}}{{maxLength=200}}
     */
    @org.hibernate.validator.constraints.Length(min = 10, max = 200)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="text", title="")
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_text_array</code>.
     */
    public ExampleRecord setTextArray(String... value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_text_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="textArray")
    public String[] getTextArray() {
        return (String[]) get(3);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_string</code>. {{minLength=4}}
     */
    public ExampleRecord setString(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_string</code>. {{minLength=4}}
     */
    @org.hibernate.validator.constraints.Length(min = 4, max = 20)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="string", title="")
    public String getString() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_string_array</code>.
     */
    public ExampleRecord setStringArray(String... value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_string_array</code>.
     */
    @org.hibernate.validator.constraints.Length(max = 20)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="stringArray")
    public String[] getStringArray() {
        return (String[]) get(5);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_short_value</code>.
     */
    public ExampleRecord setShortValue(Short value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_short_value</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortValue")
    public Short getShortValue() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_short_array</code>.
     */
    public ExampleRecord setShortArray(Short... value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_short_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortArray")
    public Short[] getShortArray() {
        return (Short[]) get(7);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_integer_value</code>.
     */
    public ExampleRecord setIntegerValue(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_integer_value</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="integerValue")
    public Integer getIntegerValue() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_integer_array</code>.
     */
    public ExampleRecord setIntegerArray(Integer... value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_integer_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="integerArray")
    public Integer[] getIntegerArray() {
        return (Integer[]) get(9);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_long_value</code>.
     */
    public ExampleRecord setLongValue(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_long_value</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longValue")
    public Long getLongValue() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_long_array</code>.
     */
    public ExampleRecord setLongArray(Long... value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_long_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longArray")
    public Long[] getLongArray() {
        return (Long[]) get(11);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_float_value</code>.
     */
    public ExampleRecord setFloatValue(Float value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_float_value</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="floatValue")
    public Float getFloatValue() {
        return (Float) get(12);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_float_array</code>.
     */
    public ExampleRecord setFloatArray(Float... value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_float_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="floatArray")
    public Float[] getFloatArray() {
        return (Float[]) get(13);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_double_value</code>.
     */
    public ExampleRecord setDoubleValue(Double value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_double_value</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="doubleValue")
    public Double getDoubleValue() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_double_array</code>.
     */
    public ExampleRecord setDoubleArray(Double... value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_double_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="doubleArray")
    public Double[] getDoubleArray() {
        return (Double[]) get(15);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_boolean_value</code>.
     */
    public ExampleRecord setBooleanValue(Boolean value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_boolean_value</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="booleanValue")
    public Boolean getBooleanValue() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_boolean_array</code>.
     */
    public ExampleRecord setBooleanArray(Boolean... value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_boolean_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="booleanArray")
    public Boolean[] getBooleanArray() {
        return (Boolean[]) get(17);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_date</code>.
     */
    public ExampleRecord setDate(LocalDate value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_date</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="date")
    public LocalDate getDate() {
        return (LocalDate) get(18);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_date_array</code>.
     */
    public ExampleRecord setDateArray(LocalDate... value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_date_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateArray")
    public LocalDate[] getDateArray() {
        return (LocalDate[]) get(19);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_time</code>.
     */
    public ExampleRecord setTime(LocalTime value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_time</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="time")
    public LocalTime getTime() {
        return (LocalTime) get(20);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_time_array</code>.
     */
    public ExampleRecord setTimeArray(LocalTime... value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_time_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timeArray")
    public LocalTime[] getTimeArray() {
        return (LocalTime[]) get(21);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_timetz</code>.
     */
    public ExampleRecord setTimetz(OffsetTime value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_timetz</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timetz")
    public OffsetTime getTimetz() {
        return (OffsetTime) get(22);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_timetz_array</code>.
     */
    public ExampleRecord setTimetzArray(OffsetTime... value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_timetz_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="timetzArray")
    public OffsetTime[] getTimetzArray() {
        return (OffsetTime[]) get(23);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_date_time</code>.
     */
    public ExampleRecord setDateTime(LocalDateTime value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_date_time</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTime")
    public LocalDateTime getDateTime() {
        return (LocalDateTime) get(24);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_date_time_array</code>.
     */
    public ExampleRecord setDateTimeArray(LocalDateTime... value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_date_time_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimeArray")
    public LocalDateTime[] getDateTimeArray() {
        return (LocalDateTime[]) get(25);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_date_timetz</code>.
     */
    public ExampleRecord setDateTimetz(OffsetDateTime value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_date_timetz</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimetz")
    public OffsetDateTime getDateTimetz() {
        return (OffsetDateTime) get(26);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_date_timetz_array</code>.
     */
    public ExampleRecord setDateTimetzArray(OffsetDateTime... value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_date_timetz_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="dateTimetzArray")
    public OffsetDateTime[] getDateTimetzArray() {
        return (OffsetDateTime[]) get(27);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_jsonb</code>.
     */
    public ExampleRecord setJsonb(TestDTO value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_jsonb</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="jsonb")
    public TestDTO getJsonb() {
        return (TestDTO) get(28);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_point</code>.
     */
    public ExampleRecord setPoint(PointDTO value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_point</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="point")
    public PointDTO getPoint() {
        return (PointDTO) get(29);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_point_array</code>.
     */
    public ExampleRecord setPointArray(PointDTO... value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_point_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="pointArray")
    public PointDTO[] getPointArray() {
        return (PointDTO[]) get(30);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_line</code>.
     */
    public ExampleRecord setLine(LineDTO value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_line</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="line")
    public LineDTO getLine() {
        return (LineDTO) get(31);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_line_array</code>.
     */
    public ExampleRecord setLineArray(LineDTO... value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_line_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineArray")
    public LineDTO[] getLineArray() {
        return (LineDTO[]) get(32);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_line_segment</code>.
     */
    public ExampleRecord setLineSegment(LineSegmentDTO value) {
        set(33, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_line_segment</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineSegment")
    public LineSegmentDTO getLineSegment() {
        return (LineSegmentDTO) get(33);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_line_segment_array</code>.
     */
    public ExampleRecord setLineSegmentArray(LineSegmentDTO... value) {
        set(34, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_line_segment_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="lineSegmentArray")
    public LineSegmentDTO[] getLineSegmentArray() {
        return (LineSegmentDTO[]) get(34);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_box</code>.
     */
    public ExampleRecord setBox(BoxDTO value) {
        set(35, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_box</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="box")
    public BoxDTO getBox() {
        return (BoxDTO) get(35);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_box_array</code>.
     */
    public ExampleRecord setBoxArray(BoxDTO... value) {
        set(36, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_box_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="boxArray")
    public BoxDTO[] getBoxArray() {
        return (BoxDTO[]) get(36);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_path</code>.
     */
    public ExampleRecord setPath(PathDTO value) {
        set(37, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_path</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="path")
    public PathDTO getPath() {
        return (PathDTO) get(37);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_path_array</code>.
     */
    public ExampleRecord setPathArray(PathDTO... value) {
        set(38, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_path_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="pathArray")
    public PathDTO[] getPathArray() {
        return (PathDTO[]) get(38);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_polygon</code>.
     */
    public ExampleRecord setPolygon(PolygonDTO value) {
        set(39, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_polygon</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="polygon")
    public PolygonDTO getPolygon() {
        return (PolygonDTO) get(39);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_polygon_array</code>.
     */
    public ExampleRecord setPolygonArray(PolygonDTO... value) {
        set(40, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_polygon_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="polygonArray")
    public PolygonDTO[] getPolygonArray() {
        return (PolygonDTO[]) get(40);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_circle</code>.
     */
    public ExampleRecord setCircle(CircleDTO value) {
        set(41, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_circle</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="circle")
    public CircleDTO getCircle() {
        return (CircleDTO) get(41);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_circle_array</code>.
     */
    public ExampleRecord setCircleArray(CircleDTO... value) {
        set(42, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_circle_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="circleArray")
    public CircleDTO[] getCircleArray() {
        return (CircleDTO[]) get(42);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_name</code>.
     */
    public ExampleRecord setName(String value) {
        set(43, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_name</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="name")
    public String getName() {
        return (String) get(43);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_name_array</code>.
     */
    public ExampleRecord setNameArray(String... value) {
        set(44, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_name_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="nameArray")
    public String[] getNameArray() {
        return (String[]) get(44);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_interval</code>.
     */
    public ExampleRecord setInterval(IntervalDTO value) {
        set(45, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_interval</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="interval")
    public IntervalDTO getInterval() {
        return (IntervalDTO) get(45);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_interval_array</code>.
     */
    public ExampleRecord setIntervalArray(IntervalDTO... value) {
        set(46, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_interval_array</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="intervalArray")
    public IntervalDTO[] getIntervalArray() {
        return (IntervalDTO[]) get(46);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_short_serial</code>.
     */
    public ExampleRecord setShortSerial(Short value) {
        set(47, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_short_serial</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="shortSerial", defaultValue="extval(")
    public Short getShortSerial() {
        return (Short) get(47);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_serial</code>.
     */
    public ExampleRecord setSerial(Integer value) {
        set(48, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_serial</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="serial", defaultValue="extval(")
    public Integer getSerial() {
        return (Integer) get(48);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_long_serial</code>.
     */
    public ExampleRecord setLongSerial(Long value) {
        set(49, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_long_serial</code>.
     */
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="longSerial", defaultValue="extval(")
    public Long getLongSerial() {
        return (Long) get(49);
    }

    /**
     * Setter for <code>pgaccess.p_example.e_state</code>.
     */
    public ExampleRecord setState(String value) {
        set(50, value);
        return this;
    }

    /**
     * Getter for <code>pgaccess.p_example.e_state</code>.
     */
    @org.hibernate.validator.constraints.Length(max = 3)
    @io.swagger.v3.oas.annotations.media.Schema(accessMode = io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_WRITE, name="state", defaultValue="new")
    public String getState() {
        return (String) get(50);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExampleRecord
     */
    public ExampleRecord() {
        super(Example.EXAMPLE);
    }

    /**
     * Create a detached, initialised ExampleRecord
     */
    public ExampleRecord(UUID uuid, UUID[] uuidArray, String text, String[] textArray, String string, String[] stringArray, Short shortValue, Short[] shortArray, Integer integerValue, Integer[] integerArray, Long longValue, Long[] longArray, Float floatValue, Float[] floatArray, Double doubleValue, Double[] doubleArray, Boolean booleanValue, Boolean[] booleanArray, LocalDate date, LocalDate[] dateArray, LocalTime time, LocalTime[] timeArray, OffsetTime timetz, OffsetTime[] timetzArray, LocalDateTime dateTime, LocalDateTime[] dateTimeArray, OffsetDateTime dateTimetz, OffsetDateTime[] dateTimetzArray, TestDTO jsonb, PointDTO point, PointDTO[] pointArray, LineDTO line, LineDTO[] lineArray, LineSegmentDTO lineSegment, LineSegmentDTO[] lineSegmentArray, BoxDTO box, BoxDTO[] boxArray, PathDTO path, PathDTO[] pathArray, PolygonDTO polygon, PolygonDTO[] polygonArray, CircleDTO circle, CircleDTO[] circleArray, String name, String[] nameArray, IntervalDTO interval, IntervalDTO[] intervalArray, Short shortSerial, Integer serial, Long longSerial, String state) {
        super(Example.EXAMPLE);

        set(0, uuid);
        set(1, uuidArray);
        set(2, text);
        set(3, textArray);
        set(4, string);
        set(5, stringArray);
        set(6, shortValue);
        set(7, shortArray);
        set(8, integerValue);
        set(9, integerArray);
        set(10, longValue);
        set(11, longArray);
        set(12, floatValue);
        set(13, floatArray);
        set(14, doubleValue);
        set(15, doubleArray);
        set(16, booleanValue);
        set(17, booleanArray);
        set(18, date);
        set(19, dateArray);
        set(20, time);
        set(21, timeArray);
        set(22, timetz);
        set(23, timetzArray);
        set(24, dateTime);
        set(25, dateTimeArray);
        set(26, dateTimetz);
        set(27, dateTimetzArray);
        set(28, jsonb);
        set(29, point);
        set(30, pointArray);
        set(31, line);
        set(32, lineArray);
        set(33, lineSegment);
        set(34, lineSegmentArray);
        set(35, box);
        set(36, boxArray);
        set(37, path);
        set(38, pathArray);
        set(39, polygon);
        set(40, polygonArray);
        set(41, circle);
        set(42, circleArray);
        set(43, name);
        set(44, nameArray);
        set(45, interval);
        set(46, intervalArray);
        set(47, shortSerial);
        set(48, serial);
        set(49, longSerial);
        set(50, state);
    }
}
